import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex flex-row'>
					<div className='min-h-screen w-[300px]  bg-emerald-700 text-white'>
						<Nav />
					</div>
					<div className='w-full min-h-screen flex justify-center items-center border border-green-600'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
